// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace MyRecipe.Model
{

    public partial class CookShowItem
    {
        public string name { get; set; }
        public string img { get; set; }
        public string images { get; set; }
        public string tag { get; set; }
        public string food { get; set; }
        public string message { get; set; }
        public string description { get; set; }
        public string keywords { get; set; }
        public int count { get; set; }
        public int fcount { get; set; }
        public int rcount { get; set; }
        public int id { get; set; }
    }

}
