// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace MyRecipe.Model
{

    public partial class FoodShowItem
    {
        public int id { get; set; }
        public string name { get; set; }//名称
        public string food { get; set; }//食物
        public string img { get; set; }//图片
        public string message { get; set; }
        public string description { get; set; }//描述
        public string keywords { get; set; }//关键字
        public string summary { get; set; }//资讯内容
        public string disease { get; set; }
        public int count { get; set; }//访问次数
        public int fcount { get; set; }//收藏数
        public int rcount { get; set; }//评论读数
        
    }

}
